version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'onda-verde'
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
